### ISSUE TITLE
[-v] rds filter/action - filter storage metrics, resize

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#13]
Picking up from https://github.com/whit537/cloud-custodian/pull/11 for https://github.com/capitalone/cloud-custodian/pull/1051 for https://github.com/capitalone/cloud-custodian/pull/934.

### Todo

- [x] use [waiters](http://boto3.readthedocs.io/en/latest/reference/services/rds.html#waiters)
- [x] expose async/immediate to config
- [x] confirm that maintenance is pending
- [x] update the maintenance window so that the maintenance runs
- [x] pick up with confirmation
- [x] DRY up

**Comment by whit537** [comment]
Okay, here we go ...

```
(Pdb) client.get_waiter('db_instance_modifying')
*** ValueError: Waiter does not exist: db_instance_modifying
(Pdb)
```

**Comment by whit537** [comment]
Blorg, `OrderedDict`s. Not very reprable.

```
(Pdb) pp client._cache['waiter_config']['waiters'].keys()
[u'DBInstanceAvailable', u'DBInstanceDeleted', u'DBSnapshotCompleted']
(Pdb) pp client._cache['waiter_config']['waiters']['DBInstanceAvailable']
OrderedDict([(u'delay', 30), (u'operation', u'DescribeDBInstances'), (u'maxAttempts', 60), (u'acceptors', [OrderedDict([(u'expected', u'available'), (u'matcher', u'pathAll'), (u'state', u'success'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'deleted'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'deleting'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'failed'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'incompatible-restore'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'incompatible-parameters'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'incompatible-parameters'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')]), OrderedDict([(u'expected', u'incompatible-restore'), (u'matcher', u'pathAny'), (u'state', u'failure'), (u'argument', u'DBInstances[].DBInstanceStatus')])])])
(Pdb) pp client._cache['waiter_config']['waiters']['DBInstanceAvailable'].keys()
[u'delay', u'operation', u'maxAttempts', u'acceptors']
(Pdb)
```

**Comment by whit537** [comment]
But it looks like we should be able to insert another entry for the `modifying` state without too much trouble ...

**Comment by whit537** [comment]
Hmm ... didn't die, but didn't succeed.

```
===================================== FAILURES ======================================
_____________________________ Resize.test_can_resize_up _____________________________
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_rds.py", line 875, in test_can_resize_up
    self.assertEqual(db['AllocatedStorage'], 6)  # nearest gigabyte
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 5 != 6
```

**Comment by whit537** [comment]
So that sure looks like it's not waiting properly for the `modifying` state, it's coming up available too quickly and reading as unmodified (still 5 GB).

**Comment by whit537** [comment]
Okay, fixed that (I'm pretty sure) but I'm getting an occasional(?) failure from the first `available` waiter, something about a bad state but it doesn't tell me what the state is. :-/

**Comment by whit537** [comment]
Ah, I think I see: have to filter down to just one db, otherwise the previous test run's db that is being deleted chokes it up. Hypothesis, anyway.

**Comment by whit537** [comment]
```
============================ 1 passed in 1715.23 seconds ============================
```

**Comment by whit537** [comment]
Now for `ApplyImmediately` config ...

**Comment by whit537** [comment]
Not getting into `process`?

**Comment by whit537** [comment]
Hmm ... still ...

**Comment by whit537** [comment]
Does the lack of processing have to do with recording vs. replaying?

**Comment by whit537** [comment]
Um ... wth?

```
_______________________________________ Resize.test_can_resize_up _______________________________________
Traceback (most recent call last):
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_rds.py", line 857, in test_can_resize_up
    self.wait_until(waiting_client, dbid, 'available')
  File "/Users/whit537/workbench/capitalone/cloud-custodian/tests/test_rds.py", line 830, in wait_until
    waiter.wait(Filters=[{'Name': 'db-instance-id', 'Value': dbid}])
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/waiter.py", line 295, in wait
    response = self._operation_method(**kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/waiter.py", line 84, in __call__
    return self._client_method(**kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 517, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/client.py", line 572, in _convert_to_request_dict
    api_params, operation_model)
  File "/Users/whit537/workbench/capitalone/cloud-custodian/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Missing required parameter in Filters[0]: "Values"
Unknown parameter in Filters[0]: "Value", must be one of: Name, Values
======================================= 1 failed in 7.06 seconds ========================================
```

**Comment by whit537** [comment]
Blorg. How did this pass yesterday? 😞

**Comment by whit537** [comment]
Re-recording w/ a fixed `Value` &rarr; `Values`, I do get into process.

**Comment by whit537** [comment]
It passed. Replaying ...

**Comment by whit537** [comment]
Passes.

**Comment by whit537** [comment]
But I still don't get into process when replaying. Hmm ... :thinking:

**Comment by whit537** [comment]
I'm trying to get into process when replaying in order to work on the `immediate` knob.

**Comment by whit537** [comment]
Without a 20 minute test cycle. 😩

**Comment by whit537** [comment]
Now ... why does `process` get called when recording but not when replaying?

**Comment by whit537** [comment]
How is it _supposed_ to work? Why doesn't it?

**Comment by whit537** [comment]
[`resources`](https://github.com/capitalone/cloud-custodian/blob/4045b0353e140072d6bd1b676a150e911ee52b24/c7n/policy.py#L211) is coming up empty. That doesn't seem right ...

**Comment by whit537** [comment]
I think we're getting the `waiting_client` in [`filter`](https://github.com/capitalone/cloud-custodian/blob/4045b0353e140072d6bd1b676a150e911ee52b24/c7n/query.py#L48-L69) instead of the record/replay one?

```
(Pdb) self.session_factory
<function <lambda> at 0x10d3e7758>
(Pdb) l
 47     
 48         def filter(self, resource_type, **params):
 49             """Query a set of resources."""
 50             import pdb; pdb.set_trace()
 51             m = self.resolve(resource_type)
 52  ->         client = local_session(self.session_factory).client(
 53                 m.service)
 54             enum_op, path, extra_args = m.enum_spec
 55             if extra_args:
 56                 params.update(extra_args)
 57     
(Pdb)
```

**Comment by whit537** [comment]
Hmmm ... that doesn't sound right. `session_factory` is not a client.

**Comment by whit537** [comment]
Something with `local_session`?

**Comment by whit537** [comment]
Suuure looks like we're getting `data` back ... :thinking:

```
(Pdb) data
[{u'PubliclyAccessible': True, u'MasterUsername': u'eric', u'EngineVersion': u'10.0.24', u'LicenseModel': u'general-public-license', u'VpcSecurityGroups': [{u'Status': u'active', u'VpcSecurityGroupId': u'sg-f9cc4d9f'}], u'InstanceCreateTime': datetime.datetime(2017, 4, 8, 10, 49, 55, 884000), u'CopyTagsToSnapshot': False, u'OptionGroupMemberships': [{u'Status': u'in-sync', u'OptionGroupName': u'default:mariadb-10-0'}], u'PendingModifiedValues': {}, u'Engine': u'mariadb', u'MultiAZ': False, u'DBSecurityGroups': [], u'DBParameterGroups': [{u'DBParameterGroupName': u'default.mariadb10.0', u'ParameterApplyStatus': u'in-sync'}], u'AutoMinorVersionUpgrade': True, u'PreferredBackupWindow': u'07:35-08:05', u'DBSubnetGroup': {u'Subnets': [{u'SubnetStatus': u'Active', u'SubnetIdentifier': u'subnet-15452171', u'SubnetAvailabilityZone': {u'Name': u'us-west-2a'}}, {u'SubnetStatus': u'Active', u'SubnetIdentifier': u'subnet-63c97615', u'SubnetAvailabilityZone': {u'Name': u'us-west-2b'}}, {u'SubnetStatus': u'Active', u'SubnetIdentifier': u'subnet-5fb47507', u'SubnetAvailabilityZone': {u'Name': u'us-west-2c'}}], u'DBSubnetGroupName': u'default', u'VpcId': u'vpc-4a9ff72e', u'DBSubnetGroupDescription': u'default', u'SubnetGroupStatus': u'Complete'}, u'ReadReplicaDBInstanceIdentifiers': [], u'AllocatedStorage': 5, u'DBInstanceArn': u'arn:aws:rds:us-west-2:644160558196:db:test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a', u'BackupRetentionPeriod': 0, u'PreferredMaintenanceWindow': u'mon:12:56-mon:13:26', u'Endpoint': {u'HostedZoneId': u'Z1PVIF0B656C1W', u'Port': 3306, u'Address': u'test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a.cnhganveedh2.us-west-2.rds.amazonaws.com'}, u'DBInstanceStatus': u'available', u'MonitoringInterval': 0, u'AvailabilityZone': u'us-west-2c', u'DomainMemberships': [], u'StorageType': u'standard', u'DbiResourceId': u'db-JUMKVRGICGPA4ZZWFI5MQJOO5Q', u'CACertificateIdentifier': u'rds-ca-2015', u'StorageEncrypted': False, u'DBInstanceClass': u'db.r3.large', u'DbInstancePort': 0, u'DBInstanceIdentifier': u'test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a'}]
(Pdb) l
 65             if path:
 66                 path = jmespath.compile(path)
 67                 data = path.search(data)
 68             if data is None:
 69                 data = []
 70  ->         return data
 71     
 72         def get(self, resource_type, identities):
 73             """Get resources by identities
 74             """
 75             m = self.resolve(resource_type)
(Pdb)
```

**Comment by whit537** [comment]
Maybe something in filtering then?

```
(Pdb) l
286     
287             if query is None:
288                 query = {}
289     
290             resources = self.augment(self.source.resources(query))
291  ->         self._cache.save(key, resources)
292             return self.filter_resources(resources)
293     
294         def get_resources(self, ids, cache=True):
295             key = {'region': self.config.region,
296                    'resource': str(self.__class__.__name__),
(Pdb) resources
[{u'PubliclyAccessible': True, u'MasterUsername': u'eric', u'EngineVersion': u'10.0.24', u'LicenseModel': u'general-public-license', u'VpcSecurityGroups': [{u'Status': u'active', u'VpcSecurityGroupId': u'sg-f9cc4d9f'}], u'InstanceCreateTime': datetime.datetime(2017, 4, 8, 10, 49, 55, 884000), u'CopyTagsToSnapshot': False, u'OptionGroupMemberships': [{u'Status': u'in-sync', u'OptionGroupName': u'default:mariadb-10-0'}], u'PendingModifiedValues': {}, u'Engine': u'mariadb', u'MultiAZ': False, u'DBSecurityGroups': [], u'DBParameterGroups': [{u'DBParameterGroupName': u'default.mariadb10.0', u'ParameterApplyStatus': u'in-sync'}], 'Tags': [], u'AutoMinorVersionUpgrade': True, u'PreferredBackupWindow': u'07:35-08:05', u'DBSubnetGroup': {u'Subnets': [{u'SubnetStatus': u'Active', u'SubnetIdentifier': u'subnet-15452171', u'SubnetAvailabilityZone': {u'Name': u'us-west-2a'}}, {u'SubnetStatus': u'Active', u'SubnetIdentifier': u'subnet-63c97615', u'SubnetAvailabilityZone': {u'Name': u'us-west-2b'}}, {u'SubnetStatus': u'Active', u'SubnetIdentifier': u'subnet-5fb47507', u'SubnetAvailabilityZone': {u'Name': u'us-west-2c'}}], u'DBSubnetGroupName': u'default', u'VpcId': u'vpc-4a9ff72e', u'DBSubnetGroupDescription': u'default', u'SubnetGroupStatus': u'Complete'}, u'ReadReplicaDBInstanceIdentifiers': [], u'AllocatedStorage': 5, u'DBInstanceArn': u'arn:aws:rds:us-west-2:644160558196:db:test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a', u'BackupRetentionPeriod': 0, u'PreferredMaintenanceWindow': u'mon:12:56-mon:13:26', u'Endpoint': {u'HostedZoneId': u'Z1PVIF0B656C1W', u'Port': 3306, u'Address': u'test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a.cnhganveedh2.us-west-2.rds.amazonaws.com'}, u'DBInstanceStatus': u'available', u'MonitoringInterval': 0, u'AvailabilityZone': u'us-west-2c', u'DomainMemberships': [], u'StorageType': u'standard', u'DbiResourceId': u'db-JUMKVRGICGPA4ZZWFI5MQJOO5Q', u'CACertificateIdentifier': u'rds-ca-2015', u'StorageEncrypted': False, u'DBInstanceClass': u'db.r3.large', u'DbInstancePort': 0, u'DBInstanceIdentifier': u'test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a'}]
(Pdb)
```

**Comment by whit537** [comment]
Yeah, looks that way.

```
(Pdb) l 87
 82             for f in self.filters:
 83                 if not resources:
 84                     break
 85                 rcount = len(resources)
 86                 resources = f.process(resources, event)
 87  ->             if event and event.get('debug', False):
 88                     self.log.debug(
 89                         "applied filter %s %d->%d", f, rcount, len(resources))
 90             self.log.debug("Filtered from %d to %d %s" % (
 91                 original, len(resources), self.__class__.__name__.lower()))
 92             return resources
(Pdb) resources
[]
(Pdb)
```

**Comment by whit537** [comment]
I'm down into [`match`](https://github.com/capitalone/cloud-custodian/blob/4045b0353e140072d6bd1b676a150e911ee52b24/c7n/filters/core.py#L361-L407) &hellip;

**Comment by whit537** [comment]
```
(Pdb) self.data
{'type': 'value', 'value': 'test-3d3394a7-c2a7-4750-9145-36e5a11453bd', 'key': 'DBInstanceIdentifier'}
(Pdb)
```

**Comment by whit537** [comment]
```
(Pdb) l
386                 v, r = self.process_value_type(self.v, r)
387             else:
388                 v = self.v
389     
390             # Value match
391  ->         if r is None and v == 'absent':
392                 return True
393             elif r is not None and v == 'present':
394                 return True
395             elif v == 'not-null' and r:
396                 return True
(Pdb) pp r
u'test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a'
(Pdb) pp v
'test-3d3394a7-c2a7-4750-9145-36e5a11453bd'
(Pdb)
```

**Comment by whit537** [comment]
Okay! What gives?

```
(Pdb) l
400                 op = OPERATORS[self.op]
401                 try:
402                     return op(r, v)
403                 except TypeError:
404                     return False
405  ->         elif r == self.v:
406                 return True
407     
408             return False
409     
410         def process_value_type(self, sentinel, value):
(Pdb) pp r == self.v
False
(Pdb) pp r
u'test-0da9a27d-ec4f-46e2-ba1e-7ce2c4bf951a'
(Pdb) pp self.v
'test-3d3394a7-c2a7-4750-9145-36e5a11453bd'
(Pdb)
```

**Comment by whit537** [comment]
Oh! We make a new one every time, ya?

```
(Pdb) l
863                     'key': 'DBInstanceIdentifier', 'value': dbid}],
864                 'actions': [{'type': 'resize', 'percent': 10}]},
865                 config={'region': 'us-west-2'},
866                 session_factory=session_factory)
867             import pdb; pdb.set_trace()
868  ->         policy.run()
869             self.wait_until(waiting_client, dbid, 'modifying')
870     
871             self.wait_until(waiting_client, dbid, 'available')
872             db = client.describe_db_instances(
873                 DBInstanceIdentifier=dbid)['DBInstances'][0]
(Pdb) pp dbid
'test-4b81e32c-6322-4d37-9976-9c535e4a1a0e'
(Pdb)
```

**Comment by whit537** [comment]
So maybe somehow we record that uuid when we freeze everything else?

**Comment by whit537** [comment]
Usually I think what we do is use non-random tokens, like `test-rds` or something. That was messing me up earlier with test reruns because I had to wait for cleanup before rerun.

**Comment by whit537** [comment]
But maybe we pull an id out of the recorded json in the replay case?

**Comment by whit537** [comment]
Blam.

**Comment by whit537** [comment]
Still works on re-record as well. Okay!

**Comment by whit537** [comment]
Now ... `ApplyImmediately`?

**Comment by whit537** [comment]
Alright, `immediately` should be `False` by default, in which case it should go to the maintenance window.

**Comment by whit537** [comment]
Test for modified schema ...

**Comment by whit537** [comment]
Started running a test for async w/ a set_trace in it, reading up on maintenance windows ...

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html

**Comment by whit537** [comment]
I guess the thing to do is run the policy, confirm that maintenance is pending, and then update the maintenance window so that the maintenance runs, then pick up with confirmation.

**Comment by whit537** [comment]
http://boto3.readthedocs.io/en/latest/reference/services/rds.html#RDS.Client.describe_pending_maintenance_actions

**Comment by whit537** [comment]
Hmm ... are resizes _supposed_ to be listed as pending maintenance?

```
(Pdb) client.describe_pending_maintenance_actions(ResourceIdentifier='arn:aws:rds:us-west-2:644160558196:db:test-3084ecb7-fa6b-43e5-a515-245ee7d4815f')
2017-04-11 05:10:02,384 - placebo.pill - DEBUG - _record_data
2017-04-11 05:10:02,385 - placebo.pill - DEBUG - save_response: rds.DescribePendingMaintenanceActions
2017-04-11 05:10:02,385 - placebo.pill - DEBUG - get_new_file_path: rds.DescribePendingMaintenanceActions
2017-04-11 05:10:02,386 - placebo.pill - DEBUG - save_response: path=/Users/whit537/workbench/capitalone/cloud-custodian/tests/data/placebo/test_rds_resize_up_asynchronously/rds.DescribePendingMaintenanceActions_3.json
{u'PendingMaintenanceActions': [], 'ResponseMetadata': {'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': 'a4d3f02c-1e96-11e7-b528-6b9ec0777dd4', 'HTTPHeaders': {'x-amzn-requestid': 'a4d3f02c-1e96-11e7-b528-6b9ec0777dd4', 'date': 'Tue, 11 Apr 2017 09:10:01 GMT', 'content-length': '367', 'content-type': 'text/xml'}}}
(Pdb)
```

**Comment by whit537** [comment]
> If this parameter is set to `false`, changes to the DB instance are applied during the next maintenance window. Some parameter changes can cause an outage and will be applied on the next call to `RebootDBInstance`, or the next failure reboot. Review the table of parameters in [Modifying a DB Instance and Using the Apply Immediately Parameter](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.DBInstance.Modifying.html) to see the impact that setting `ApplyImmediately` to `true` or `false` has for each modified parameter and to determine when the changes will be applied.

http://boto3.readthedocs.io/en/latest/reference/services/rds.html#RDS.Client.modify_db_instance

**Comment by whit537** [comment]
| DB Instance Setting | When the Change Occurs | Downtime Notes |
|:----------|:----------------|:-----------------|
| Allocated Storage | If **Apply Immediately** is set to true, the change occurs immediately.<br>If **Apply Immediately** is set to false, the change occurs during the next maintenance window. | No downtime. Performance may be degraded during the change. |

**Comment by whit537** [comment]
Oh hey! Pending modifications are separate from pending maintenance?

![screen shot 2017-04-11 at 5 25 59 am](https://cloud.githubusercontent.com/assets/134455/24902199/6ac7fb26-1e77-11e7-996d-401476dff8c7.png)

**Comment by whit537** [comment]
No `pending_mo` in http://boto3.readthedocs.io/en/latest/reference/services/rds.html.

**Comment by whit537** [comment]
I'm mucking about in the Chrome dev console on the AWS console, trying to find a hint for pending modifications.

**Comment by whit537** [comment]
Something!

![screen shot 2017-04-11 at 6 04 59 am](https://cloud.githubusercontent.com/assets/134455/24903914/de85af2c-1e7c-11e7-9d9f-9222eddab904.png)

**Comment by whit537** [comment]
Yes! It's in `describe_db_instances`. 😖 

```
(Pdb) foo['DBInstances'][0]['PendingModifiedValues']
{u'AllocatedStorage': 6}
(Pdb)
```

**Comment by whit537** [comment]
Another custom waiter, I guess?

**Comment by whit537** [comment]
More complicated than the first ...

**Comment by whit537** [comment]
P.S. Looks like I've been using magentic storage. Gonna switch to gp2 for performance.

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage

**Comment by whit537** [comment]
Now to modify maintenance window to trigger modification ... will the discrepancy between system maintenance and modification bite us?

**Comment by whit537** [comment]
Inside the modification pending waiter:

```
(Pdb) l
192     
193             def acceptor_matches(response):
194                 if 'Error' in response:
195                     return
196                 import pdb; pdb.set_trace()
197  ->             return expression.search(response) == expected
198             return acceptor_matches
199     
200         def _create_path_all_matcher(self):
201             expression = jmespath.compile(self.argument)
202             expected = self.expected
(Pdb) expected
True
(Pdb) expression.search(response)
[{u'AllocatedStorage': 6}]
(Pdb)
```

**Comment by whit537** [comment]
Alright! Soooo ... I need a [JMESPath](http://jmespath.org/) expression for a non-empty (but otherwise unspecified) list ...

**Comment by whit537** [comment]
Possibility:

```
(Pdb) jmespath.compile('length(DBInstances[].PendingModifiedValues)').search(response)
1
```

But I also need to be able to set `expected` ...

**Comment by whit537** [comment]
Oh, that part's easy. :)

**Comment by whit537** [comment]
Erm, not easy. I want > 0, not an exact number.

**Comment by whit537** [comment]
Got it:

```
(Pdb) jmespath.compile('!!length(DBInstances[].PendingModifiedValues)').search(response)
True
```

**Comment by whit537** [comment]
💃 

![screen shot 2017-04-13 at 6 31 59 am](https://cloud.githubusercontent.com/assets/134455/25001310/ecf60600-2012-11e7-9f61-592121af0d31.png)

**Comment by whit537** [comment]
Also twice as fast with gp2. 👍

**Comment by whit537** [comment]
https://github.com/capitalone/cloud-custodian/pull/1051 merged!
