### ISSUE TITLE
[-v] CI - run functional tests against live AWS

### ISSUE THREAD

**Issue by whit537** [whit537/cloud-custodian#5]
https://github.com/capitalone/cloud-custodian/issues/903

### Todo

- [x] switch to pytest: https://github.com/capitalone/cloud-custodian/pull/1007
  - [x] `requirements-dev.txt`
  - [x] `Makefile`
    - [x] `coverage`
    - [x] `ttest`
    - [x] `test`
    - [x] `ftests` &larr; is this us? "functional" tests?
  - [x] `.drone.yml`
  - [x] `.travis.yml`
- [x] mark tests in `test_vpc.py`

**Comment by whit537** [comment]
> so i think we need a decorator for tests that are self contained, so that we can use that to mark / filter out tests that we can reuse for functional tests. a good portion of the vpc tests are setup that way (zero pre-context on the record).

**Comment by whit537** [comment]
From Gitter:

> i'd like to start decorating self contained tests as such so we can do a functional test run, the open question is whats needed to integrate the decoratored tests with the testrunner

> which brings up another topic re testrunners.. we're currently using nosetests, which works, but has been dead upstream for a while. i checked out pytest which was pretty reasonable.

> its the opposite of what most of the test runner filters do, they do exclusion based filters, we want inclusion filters .. s/filters/decorators

> our unit tests can be reused as is as functional tests for a subset of them that don't have context

**Comment by whit537** [comment]
http://stackoverflow.com/questions/35025591/with-py-test-what-is-the-best-way-to-do-test-inclusion-exclusion-from-the-comma
http://doc.pytest.org/en/latest/usage.html
http://doc.pytest.org/en/latest/example/markers.html

**Comment by whit537** [comment]
[Custom markers](http://doc.pytest.org/en/latest/example/markers.html) look really promising ...

**Comment by whit537** [comment]
Yeah, this looks trivial.

**Comment by whit537** [comment]
Well, now the question is: which tests should be marked? 😁

**Comment by whit537** [comment]
> self contained tests
> a subset of them that don't have context
> a good portion of the vpc tests are setup that way (zero pre-context on the record).

**Comment by whit537** [comment]
> tests that are free of external modalities (iam, security groups, etc) and fully self-contained.
> most of the vpc tests have been written in that style, where they create their test conditions from scratch. create vpcs, sgs, enis, etc.

https://github.com/capitalone/cloud-custodian/issues/903#issuecomment-277506811

**Comment by whit537** [comment]
I've started a todo in the ticket description.

**Comment by whit537** [comment]
[`make test`](https://gist.github.com/whit537/5ddd673e475c2d148b83638e885720f1)

**Comment by whit537** [comment]
[`AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=us-east-1 nosetests tests`](https://gist.github.com/whit537/fd592936e2ba1c1a785d8b17ce1131df)

**Comment by whit537** [comment]
`AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=us-east-1 py.test -n auto tests` with `pytest-xdist`:

https://gist.github.com/whit537/690224e2f5c5ce8ef747112eb3ad0441

**Comment by whit537** [comment]
No timeouts. Six DynamoDB failures.

**Comment by whit537** [comment]
How about `ttest`?

http://doc.pytest.org/en/latest/example/simple.html#profiling-test-duration

[`AWS_DEFAULT_REGION=us-east-1 pytest --durations=20 tests`](https://gist.github.com/whit537/3db436bab29f7308ba963fead4b3ea0a)

```
========================== slowest 20 test durations ===========================
1.75s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_autopatch
1.74s call     workbench/capitalone/cloud-custodian/tests/test_cli.py::ValidateTest::test_validate
1.66s call     workbench/capitalone/cloud-custodian/tests/test_ami.py::TestAMI::test_unused_ami_false
1.49s call     workbench/capitalone/cloud-custodian/tests/test_mu.py::PolicyLambdaProvision::test_cwe_asg_instance
1.39s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::VpcTest::test_flow_logs
1.31s call     workbench/capitalone/cloud-custodian/tests/test_cfn.py::TestCFN::test_delete
1.16s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_attach_encrypt
1.16s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::TestModifyVpcSecurityGroupsAction::test_rds_add_security_group
0.86s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::TestModifyVpcSecurityGroupsAction::test_rds_remove_matched_security_groups
0.78s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_encrypt_keys
0.73s call     workbench/capitalone/cloud-custodian/tests/test_mu.py::PolicyLambdaProvision::test_sns_subscriber
0.63s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::BucketDelete::test_delete_bucket_with_failure
0.61s call     workbench/capitalone/cloud-custodian/tests/test_asg.py::AutoScalingTest::test_asg_invalid_filter_bad
0.59s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestModifyVpcSecurityGroupsAction::test_elasticache_add_security_group
0.56s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_used
0.56s call     workbench/capitalone/cloud-custodian/tests/test_asg.py::AutoScalingTest::test_asg_invalid_filter_good
0.56s call     workbench/capitalone/cloud-custodian/tests/test_policy.py::TestPolicy::test_load_policy_validation_error
0.55s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_default_vpc
0.55s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_stale
0.55s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestModifyVpcSecurityGroupsAction::test_elasticache_remove_matched_security_groups
```

**Comment by whit537** [comment]
Let's go for 100:

https://gist.github.com/whit537/adaf851e6668d1d0a3ed73be4c4d33e1

```
========================== slowest 100 test durations ==========================
1.80s call     workbench/capitalone/cloud-custodian/tests/test_cli.py::ValidateTest::test_validate
1.60s call     workbench/capitalone/cloud-custodian/tests/test_notify.py::NotifyTest::test_notify
1.56s call     workbench/capitalone/cloud-custodian/tests/test_cli.py::MetricsTest::test_metrics
1.41s call     workbench/capitalone/cloud-custodian/tests/test_query.py::ResourceQueryTest::test_query_filter
1.38s call     workbench/capitalone/cloud-custodian/tests/test_code.py::CodeBuild::test_query_builds
1.35s call     workbench/capitalone/cloud-custodian/tests/test_mu.py::PolicyLambdaProvision::test_cwe_asg_instance
1.18s call     workbench/capitalone/cloud-custodian/tests/test_kinesis.py::Kinesis::test_hose_delete
0.84s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSSnapshotTest::test_rds_snapshot_access
0.80s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestModifySecurityGroupsActionSchema::test_invalid_isolation_group_params
0.77s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_encrypt_keys
0.77s call     workbench/capitalone/cloud-custodian/tests/test_rdscluster.py::RDSClusterTest::test_rdscluster_simple_filter
0.72s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::TestModifyVpcSecurityGroupsAction::test_rds_add_security_group
0.71s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestModifyVpcSecurityGroupsAction::test_elasticache_remove_matched_security_groups
0.70s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestModifyVpcSecurityGroupsAction::test_elasticache_add_security_group
0.70s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::TestModifyVpcSecurityGroupsAction::test_rds_remove_matched_security_groups
0.69s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::BucketDelete::test_delete_bucket_with_failure
0.67s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_unused
0.65s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_minor_upgrade_unavailable
0.64s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::VpcTest::test_flow_logs
0.61s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_attach_encrypt
0.61s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestElastiCacheCluster::test_elasticache_subnet_filter
0.61s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::EncryptExtantVolumesTest::test_encrypt_volumes
0.57s call     workbench/capitalone/cloud-custodian/tests/test_mu.py::PolicyLambdaProvision::test_sns_subscriber
0.55s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_mark_and_match
0.54s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_default_vpc
0.54s call     workbench/capitalone/cloud-custodian/tests/test_iam.py::IamRoleFilterUsage::test_iam_role_inuse
0.53s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSSnapshotTest::test_rds_cross_region_copy_many
0.53s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_only_ports
0.52s call     workbench/capitalone/cloud-custodian/tests/test_ami.py::TestAMI::test_unused_ami_false
0.52s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_used
0.51s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestElastiCacheCluster::test_elasticache_security_group
0.51s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_tag_trim
0.50s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_self_reference
0.50s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::TestHealthEventsFilter::test_rds_health_events_filter
0.50s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_cidr_size_egress
0.50s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::NetworkInterfaceTest::test_interface_subnet
0.49s call     workbench/capitalone/cloud-custodian/tests/test_asg.py::AutoScalingTest::test_asg_invalid_filter_good
0.48s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_retention
0.48s call     workbench/capitalone/cloud-custodian/tests/test_redshift.py::TestModifyVpcSecurityGroupsAction::test_redshift_add_security_group
0.48s call     workbench/capitalone/cloud-custodian/tests/test_revisions.py::SGDiffLibTest::test_sg_patch_pitr
0.48s call     workbench/capitalone/cloud-custodian/tests/test_iam.py::IamRoleFilterUsage::test_iam_role_unused
0.48s call     workbench/capitalone/cloud-custodian/tests/test_asg.py::AutoScalingTest::test_asg_invalid_filter_bad
0.48s call     workbench/capitalone/cloud-custodian/tests/test_account.py::AccountTests::test_cloudtrail_current_region_global
0.47s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::SnapshotCopyTest::test_snapshot_copy
0.47s call     workbench/capitalone/cloud-custodian/tests/test_autotag.py::AutoTagCreator::test_auto_tag_creator
0.47s call     workbench/capitalone/cloud-custodian/tests/test_redshift.py::TestRedshift::test_redshift_security_group_filter
0.46s call     workbench/capitalone/cloud-custodian/tests/test_iam.py::IamInstanceProfileFilterUsage::test_iam_instance_profile_inuse
0.46s call     workbench/capitalone/cloud-custodian/tests/test_rdscluster.py::RDSClusterTest::test_rdscluster_security_group
0.46s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_encrypt_keys_key_id_option
0.46s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::NetworkAclTest::test_s3_cidr_network_acl_present
0.46s call     workbench/capitalone/cloud-custodian/tests/test_redshift.py::TestModifyVpcSecurityGroupsAction::test_redshift_remove_matched_security_groups
0.45s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestTag::test_ec2_normalize_tag
0.45s call     workbench/capitalone/cloud-custodian/tests/test_cli.py::ReportTest::test_report
0.45s call     workbench/capitalone/cloud-custodian/tests/test_elb.py::TestDefaultVpc::test_elb_default_vpc
0.45s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_tag_and_remove
0.45s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_port_within_range
0.45s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_default_vpc
0.45s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::SnapshotTrimTest::test_snapshot_trim
0.45s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestTerminate::test_ec2_terminate
0.45s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_encrypt_versioned_bucket
0.45s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_remove_policy_none_extant
0.44s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSSnapshotTest::test_rds_snapshot_mark
0.43s call     workbench/capitalone/cloud-custodian/tests/test_cli.py::ReportTest::test_warning_on_empty_policy_filter
0.43s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestModifySecurityGroupAction::test_security_group_type
0.43s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSSnapshotTest::test_rds_latest
0.43s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestTag::test_ec2_rename_tag
0.43s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_multipart_large_file
0.43s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_snapshot
0.43s call     workbench/capitalone/cloud-custodian/tests/test_rdscluster.py::RDSClusterTest::test_rdscluster_subnet
0.42s call     workbench/capitalone/cloud-custodian/tests/test_iam.py::IamInstanceProfileFilterUsage::test_iam_instance_profile_unused
0.42s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestTagAugmentation::test_tag_augment
0.42s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSTest::test_rds_upgrade_available
0.42s call     workbench/capitalone/cloud-custodian/tests/test_s3.py::S3Test::test_enable_versioning
0.42s call     workbench/capitalone/cloud-custodian/tests/test_mu.py::PolicyLambdaProvision::test_cwl_subscriber
0.41s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestModifySecurityGroupAction::test_ec2_add_security_groups
0.41s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestTagTrim::test_ec2_tag_trim
0.41s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::CopyInstanceTagsTest::test_copy_instance_tags
0.41s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::TestKmsAlias::test_ebs_kms_alias
0.41s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSSnapshotTest::test_rds_snapshot_unmark
0.41s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestTag::test_ec2_untag
0.41s call     workbench/capitalone/cloud-custodian/tests/test_ami.py::TestAMI::test_query
0.41s call     workbench/capitalone/cloud-custodian/tests/test_redshift.py::TestRedshift::test_redshift_cluster_mark
0.41s call     workbench/capitalone/cloud-custodian/tests/test_rds.py::RDSSnapshotTest::test_rds_snapshot_tag_filter
0.40s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestMetricFilter::test_metric_filter
0.40s call     workbench/capitalone/cloud-custodian/tests/test_rdscluster.py::RDSClusterTest::test_rdscluster_retention
0.40s call     workbench/capitalone/cloud-custodian/tests/test_rdscluster.py::RDSClusterSnapshotTest::test_rdscluster_snapshot_simple_filter
0.40s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestStart::test_ec2_start
0.40s call     workbench/capitalone/cloud-custodian/tests/test_elb.py::TestModifyVpcSecurityGroupsAction::test_elb_remove_all_security_groups
0.40s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestSnapshot::test_ec2_snapshot_copy_tags
0.39s call     workbench/capitalone/cloud-custodian/tests/test_revisions.py::SGDiffLibTest::test_sg_diff_patch
0.39s call     workbench/capitalone/cloud-custodian/tests/test_elb.py::TestModifyVpcSecurityGroupsAction::test_elb_remove_security_groups
0.39s call     workbench/capitalone/cloud-custodian/tests/test_elb.py::TestModifyVpcSecurityGroupsAction::test_elb_add_security_group
0.39s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::EbsFaultToleranceTest::test_ebs_non_fault_tolerant
0.39s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestImageFilter::test_ec2_image
0.39s call     workbench/capitalone/cloud-custodian/tests/test_vpc.py::SecurityGroupTest::test_security_group_delete
0.39s call     workbench/capitalone/cloud-custodian/tests/test_appelb.py::AppELBTest::test_appelb_default_vpc_filter
0.39s call     workbench/capitalone/cloud-custodian/tests/test_lambda.py::LambdaTest::test_sg_filter
0.39s call     workbench/capitalone/cloud-custodian/tests/test_ebs.py::SnapshotAccessTest::test_snapshot_access
0.38s call     workbench/capitalone/cloud-custodian/tests/test_elasticache.py::TestElastiCacheSnapshot::test_elasticache_snapshot_age_filter
0.38s call     workbench/capitalone/cloud-custodian/tests/test_ec2.py::TestVolumeFilter::test_ec2_attached_volume_skip_block
```

**Comment by whit537** [comment]
Now for coverage ...

https://gist.github.com/whit537/01e0fa0fd5958462bb180f8bc822f163

**Comment by whit537** [comment]
Looks about right:

![screen shot 2017-03-04 at 6 53 27 am](https://cloud.githubusercontent.com/assets/134455/23578543/4d3b4ccc-00a7-11e7-9c68-8063eb9f8f60.png)

**Comment by whit537** [comment]
Pytest PR in https://github.com/capitalone/cloud-custodian/pull/1007.

**Comment by whit537** [comment]
Alright, now which of these 22 tests should be marked `functional`?

```
(cloud-custodian) $ ack 'def test' tests/test_vpc.py 
    def test_flow_logs(self):
    def test_s3_cidr_network_acl_present(self):
    def test_s3_cidr_network_acl_not_present(self):
    def test_interface_subnet(self):
    def test_id_selector(self):
    def test_stale(self):
    def test_used(self):
    def test_unused(self):
    def test_only_ports(self):
    def test_self_reference(self):
    def test_security_group_delete(self):
    def test_port_within_range(self):
    def test_ingress_remove(self):
    def test_default_vpc(self):
    def test_config_source(self):
    def test_only_ports_ingress(self):
    def test_multi_attribute_ingress(self):
    def test_ports_ingress(self):
    def test_permission_expansion(self):
    def test_cidr_ingress(self):
    def test_cidr_size_egress(self):
    def test_egress_validation_error(self):
lines 1-22/22 (END)
```

**Comment by whit537** [comment]
P.S. We're going to need to wrap the decorator somehow to avoid a hard pytest dependency: https://github.com/capitalone/cloud-custodian/pull/1007#issuecomment-284185144.

**Comment by whit537** [comment]
Initial PRs in. Closing until reprioritized.

**Comment by whit537** [comment]
&rarr; https://github.com/whit537/cloud-custodian/issues/45
